"""empty message

Revision ID: 09910212b990
Revises: eb17c47385f5
Create Date: 2022-11-17 14:14:24.322470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09910212b990'
down_revision = 'eb17c47385f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
