"""empty message

Revision ID: dac1fc249192
Revises: 7ac75f064f5d
Create Date: 2022-10-20 16:27:06.536675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac1fc249192'
down_revision = '7ac75f064f5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
