"""empty message

Revision ID: eb17c47385f5
Revises: dac1fc249192
Create Date: 2022-11-17 13:22:34.780051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb17c47385f5'
down_revision = 'dac1fc249192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
